baseURL = ""
title = "Khia A. Johnson"
languageCode = "en-us"
theme = "anatole"

customCss = ["css/style.css", "layouts/sidebar.html"]
googleAnalytics = "UA-92518846-1"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
title = "Khia A. Johnson"
author = "Khia A. Johnson"
description = "bilingual speech, corpus linguistics & experimental design"
affiliation = "phd candidate at ubc linguistics"
affiliationLink = "https://linguistics.ubc.ca/profile/khia-johnson/"
profilePicture = "/images/profile.jpg"
keywords = ["bilingualism", "speech science", "psycholinguistics", "language data", "rstats", "phonetics", "voice", "corpus linguistics"]
favicon = "/favicons/"
indexDateFormat = "Jan 2, 2006"
listDateFormat = "Jan 2"
singleDateFormat = "Jan 2, 2006"
disableThemeSwitcher = false

[params.utterances]
repo = "khiajohnson/website"
issueTerm = "pathname"
label="✨💬✨"
theme="github-light"
crossorigin="anonymous"

[[params.socialIcons]]
icon = "fas fa-university"
title = "UBC"
url = "https://linguistics.ubc.ca/profile/khia-johnson/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://www.twitter.com/khia_johnson/"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/khiajohnson/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/khiajohnson/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:khia.johnson@ubc.ca"

[menu]

  [[menu.main]]
  name = "home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "research/cv"
  weight = 200
  identifier = "cv"
  url = "/cv/"

  [[menu.main]]
  name = "archive"
  weight = 300
  identifier = "archive"
  url = "/post/"  
