baseURL: "https://khiajohnson.com/"
title: Khia Johnson, PhD
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-92518846-1

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Khia Johnson, PhD
    description: "psycholinguist & ux research scientist | personal website"
    keywords: [Blog, Portfolio, UX research, Bilingualism, Speech, Data, Rstats, Phonetics, Voice, Corpus, Linguistics, Psycholinguistics]
    author: Khia Johnson
    images: ["/images/profilewide.jpg", "/images/profilesmall.jpg"]
    DateFormat: "2 Jan 2006"
    defaultTheme: light # auto, dark, light
    disableThemeToggle: true

    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    disableSpecial1stPost: true
    disableScrollToTop: false
    comments: true #added directly to single.html
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "favicons/favicon.ico"
        favicon16x16: "favicons/favicon-16x16.png"
        favicon32x32: "favicons/favicon-32x32.png"
        apple_touch_icon: "favicons/apple-touch-icon.png"
        #safari_pinned_tab: "<link / abs url>"

    label:
        text: "Khia Johnson, PhD"
        icon: "/favicons/apple-touch-icon.png"
        iconHeight: 25

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Khia Johnson, PhD
        subtitle: she/her/hers
        bio: UX Research Scientist • Audio • Psycholinguist
        imageUrl: "/images/profilesmall.jpg"
        imageWidth: 225
        imageHeight: 225
        imageTitle: Headshot of Khia Johnson
        buttons:
            - name: "about"
              url: about
            - name: "publications"
              url: publications
            - name: "blog"
              url: post

    # home-info mode
    # homeInfoParams:
    #     Title: "Hi there \U0001F44B"
    #     Content: Welcome to my blog

    socialIcons:
        - name: mastodon
          url: "https://hci.social/web/@khia"
        - name: twitter
          url: "https://www.twitter.com/khia_johnson/"
        - name: linkedin
          url: "https://www.linkedin.com/in/khiajohnson/"
        - name: github
          url: "https://github.com/khiajohnson/"
        - name: email
          url: "mailto:hello@khiajohnson.com"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # editPost:
    #     URL: "https://github.com/<path_to_repo>/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        - identifier: about
          name: about
          url: /about/
          weight: 10
        - identifier: publications
          name: publications
          url: /publications/
          weight: 20
        - identifier: blog
          name: blog
          url: /post/
          weight: 30
        # - identifier: search
        #   name: 🔍
        #   url: search
        #   weight: 40

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: false
        style: monokailight
